### ISSUE TITLE
Axis Definition

### ISSUE THREAD

**Issue by davelab6** [Vectro-Type-Foundry/kablammo#28]
I propose tag/label as `MOVE`/`Movement`, and min/default/max of `0.0`/`1.0`/`100.0`.

The `0..100` range is meant to give the intuitive sense of a percentage, and the precision factor of 1 gives 1,000 steps, suitable for fine animation.

In this case, the https://github.com/google/fonts/tree/master/axisregistry file would be:

```
tag: "MOVE"
display_name: "Movement"
min_value: 0.0
default_value: 0.0
max_value: 100.0
precision: 1
fallback {
  name: "Start"
  value: 0.0
}
fallback {
  name: "End"
  value: 100.0
}
description: 
  "As the movement axis progresses, the letterforms move"
  " in ways specific to that typeface."
```

There may be some pushback from the GF Eng teem on this, as they prefer axes definitions to be concrete. I expect the range will stay the same, only the tag/label would change, to something more specific to the kind of movement... `SQRM`/`Squirm`?

We could do something super project specific, `BLAM`/`Kablammo` - and then it is also possible that, like with Handjet (https://github.com/rosettatype/Handjet/issues/3), we would want to use a range `1..4` with maybe 2 or 3 decimal places of precision, for 400 or 4,000 steps, but where the integer values fall on the masters.

**Comment by vv-monsalve** [comment]
Axis was defined as [MORF](https://github.com/googlefonts/axisregistry/pull/120)
